name: Automatisches Löschen gemergerter Branches

on:
  # Auslöser jede Nacht um 3 Uhr
  schedule:
    - cron: "0 3 * * *"
  # Der Workflow kann manuell über den Workflow-Dispatch-Trigger ausgelöst werden
  workflow_dispatch:

jobs:
  delete_merged_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Fetch All Branches
        run: git fetch --all --prune

      - name: Get Merged Branches
        id: merged_branches
        run: echo "::set-output name=branches::$(git branch -r --merged origin/master | cut -d '/' -f 2-)"

      - name: Delete Merged Branches
        run: |
          branches=${{ steps.merged_branches.outputs.branches }}
          IFS=$'\n' read -rd '' -a branches_array <<<"$branches"
          for branch in "${branches_array[@]}"; do
            if [[ "$branch" != "HEAD" && "$branch" != "master" ]]; then
              git push origin --delete "$branch"
            fi
          done

      - name: Sende Teams-Message
        # Das Python-Skript "teams_webhook.py" wird ausgeführt
        run: python teams_webhook.py delete
